
version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    env_file:
      - ./.env
    ports:
      - "3306:3306"

  animator-service:
    build: .
    image: yrsk/animator-service
    container_name: animator-service
    env_file:
      - ./.env
    depends_on:
      - mysql
    ports:
      - "8088:8088"
    restart: unless-stopped
